name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: uqfelipe
          outputs: dist/snake.svg

      - name: Enviar a animação para o branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
